void ah_bicubic_interpolator(int *flag, const double rr, const double th, 
		double *i_a, double *i_b, double *i_h, 
		double *i_c, double *i_phi,
		double *i_Aa, double *i_Ab, 
		double *i_Ah, double *i_Ac, 
		double *i_K,
		double *i_Dr_a, double *i_Dr_b, 
		double *i_Dr_h, double *i_Dr_c, double *i_Dr_phi,
		double *i_Dz_a, double *i_Dz_b, 
		double *i_Dz_h, double *i_Dz_c, double *i_Dz_phi,
		const double *a, 
		const double *Dr_a,
		const double *Dz_a,
		const double *Drz_a,
		const double *b, 
		const double *Dr_b,
		const double *Dz_b,
		const double *Drz_b,
		const double *h,
		const double *Dr_h,
		const double *Dz_h,
		const double *Drz_h,
		const double *c, 
		const double *Dr_c,
		const double *Dz_c,
		const double *Drz_c,
		const double *phi,
		const double *Dr_phi,
		const double *Dz_phi,
		const double *Drz_phi,
		const double *Aa, 
		const double *Dr_Aa,
		const double *Dz_Aa,
		const double *Drz_Aa,
		const double *Ab, 
		const double *Dr_Ab,
		const double *Dz_Ab,
		const double *Drz_Ab,
		const double *Ah, 
		const double *Dr_Ah,
		const double *Dz_Ah,
		const double *Drz_Ah,
		const double *Ac, 
		const double *Dr_Ac,
		const double *Dz_Ac,
		const double *Drz_Ac,
		const double *K,
		const double *Dr_K,
		const double *Dz_K,
		const double *Drz_K,
		//const double *Dr_a,
		const double *Drr_a, 
		//const double *Drz_a,
		const double *Drrz_a,
		//const double *Dr_b,
		const double *Drr_b, 
		//const double *Drz_b,
		const double *Drrz_b,
		//const double *Dr_h,
		const double *Drr_h, 
		//const double *Drz_h,
		const double *Drrz_h,
		//const double *Dr_c, 
		const double *Drr_c,
		//const doubel *Drz_c,
		const double *Drrz_c,
		//const double *Dr_phi,
		const double *Drr_phi,
		//const double *Drz_phi,
		const double *Drrz_phi,
		//const double *Dz_a,
		//const double *Drz_a, 
		const double *Dzz_a,
		const double *Drzz_a,
		//const double *Dz_b,
		//const double *Drz_b, 
		const double *Dzz_b,
		const double *Drzz_b,
		//const double *Dz_h,
		//const double *Drz_h, 
		const double *Dzz_h,
		const double *Drzz_h,
		//const double *Dz_c, 
		//const double *Drz_c,
		const double *Dzz_c,
		const double *Drzz_c,
		//const double *Dz_phi,
		//const double *Drz_phi,
		const double *Dzz_phi,
		const double *Drzz_phi);
