void general_elliptic(double *u,
	double *res,
	const double *ell_a,
	const double *ell_b,
	const double *ell_c,
	const double *ell_d,
	const double *ell_e,
	const double *ell_s,
	const double *ell_f,
	const double uInf,
	const int robin,
	const int r_sym,
	const int z_sym,
	const int perm_use,
	const int precond_use,
	const int low_rank_use);
